development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pguser
  password: pguser_password
  database: showterm
  host: localhost
 # username: pguser
 # password: pguser_password
